In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("./dataset/HIST_PAINEL_COVIDBR_13mai2021.csv", sep=";")

In [4]:
df

,regiao,estado,municipio,coduf,codmun,codRegiaoSaude,nomeRegiaoSaude,data,semanaEpi,populacaoTCU2019,casosAcumulado,casosNovos,obitosAcumulado,obitosNovos,Recuperadosnovos,emAcompanhamentoNovos,interior/metropolitana
0,Brasil,NaN,NaN,76,NaN,NaN,NaN,2020-02-25,9,210147125.0,0,0,0,0,NaN,NaN,NaN
1,Brasil,NaN,NaN,76,NaN,NaN,NaN,2020-02-26,9,210147125.0,1,1,0,0,NaN,NaN,NaN
2,Brasil,NaN,NaN,76,NaN,NaN,NaN,2020-02-27,9,210147125.0,1,0,0,0,NaN,NaN,NaN
3,Brasil,NaN,NaN,76,NaN,NaN,NaN,2020-02-28,9,210147125.0,1,0,0,0,NaN,NaN,NaN
4,Brasil,NaN,NaN,76,NaN,NaN,NaN,2020-02-29,9,210147125.0,2,1,0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2321512,Centro-Oeste,DF,Brasília,53,530010.0,53001.0,DISTRITO FEDERAL,2021-05-09,19,3015268.0,386688,925,8113,26,NaN,NaN,1.0
2321513,Centro-Oeste,DF,Brasília,53,530010.0,53001.0,DISTRITO FEDERAL,2021-05-10,19,3015268.0,387520,832,8150,37,NaN,NaN,1.0
2321514,Centro-Oeste,DF,Brasília,53,530010.0,53001.0,DISTRITO FEDERAL,2021-05-11,19,3015268.0,388286,766,8184,34,NaN,NaN,1.0
2321515,Centro-Oeste,DF,Brasília,53,530010.0,53001.0,DISTRITO FEDERAL,2021-05-12,19,3015268.0,389178,892,8217,33,NaN,NaN,1.0
2321516,Centro-Oeste,DF,Brasília,53,530010.0,53001.0,DISTRITO FEDERAL,2021-05-13,19,3015268.0,390117,939,8251,34,NaN,NaN,1.0

In [5]:
df_states = df[(~df["estado"].isna()) & (df["codmun"].isna())]

In [6]:
df_states

,regiao,estado,municipio,coduf,codmun,codRegiaoSaude,nomeRegiaoSaude,data,semanaEpi,populacaoTCU2019,casosAcumulado,casosNovos,obitosAcumulado,obitosNovos,Recuperadosnovos,emAcompanhamentoNovos,interior/metropolitana
446,Norte,RO,NaN,11,NaN,NaN,NaN,2020-02-25,9,1777225.0,0,0,0,0,NaN,NaN,NaN
447,Norte,RO,NaN,11,NaN,NaN,NaN,2020-02-26,9,1777225.0,0,0,0,0,NaN,NaN,NaN
448,Norte,RO,NaN,11,NaN,NaN,NaN,2020-02-27,9,1777225.0,0,0,0,0,NaN,NaN,NaN
449,Norte,RO,NaN,11,NaN,NaN,NaN,2020-02-28,9,1777225.0,0,0,0,0,NaN,NaN,NaN
450,Norte,RO,NaN,11,NaN,NaN,NaN,2020-02-29,9,1777225.0,0,0,0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12429,Centro-Oeste,DF,NaN,53,NaN,NaN,NaN,2021-05-09,19,3015268.0,386688,925,8113,26,NaN,NaN,NaN
12430,Centro-Oeste,DF,NaN,53,NaN,NaN,NaN,2021-05-10,19,3015268.0,387520,832,8150,37,NaN,NaN,NaN
12431,Centro-Oeste,DF,NaN,53,NaN,NaN,NaN,2021-05-11,19,3015268.0,388286,766,8184,34,NaN,NaN,NaN
12432,Centro-Oeste,DF,NaN,53,NaN,NaN,NaN,2021-05-12,19,3015268.0,389178,892,8217,33,NaN,NaN,NaN
12433,Centro-Oeste,DF,NaN,53,NaN,NaN,NaN,2021-05-13,19,3015268.0,390117,939,8251,34,NaN,NaN,NaN

In [7]:
df_brasil = df[df["regiao"] == "Brasil"]

In [8]:
df_brasil

,regiao,estado,municipio,coduf,codmun,codRegiaoSaude,nomeRegiaoSaude,data,semanaEpi,populacaoTCU2019,casosAcumulado,casosNovos,obitosAcumulado,obitosNovos,Recuperadosnovos,emAcompanhamentoNovos,interior/metropolitana
0,Brasil,NaN,NaN,76,NaN,NaN,NaN,2020-02-25,9,210147125.0,0,0,0,0,NaN,NaN,NaN
1,Brasil,NaN,NaN,76,NaN,NaN,NaN,2020-02-26,9,210147125.0,1,1,0,0,NaN,NaN,NaN
2,Brasil,NaN,NaN,76,NaN,NaN,NaN,2020-02-27,9,210147125.0,1,0,0,0,NaN,NaN,NaN
3,Brasil,NaN,NaN,76,NaN,NaN,NaN,2020-02-28,9,210147125.0,1,0,0,0,NaN,NaN,NaN
4,Brasil,NaN,NaN,76,NaN,NaN,NaN,2020-02-29,9,210147125.0,2,1,0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
441,Brasil,NaN,NaN,76,NaN,NaN,NaN,2021-05-09,19,210147125.0,15184790,38911,422340,1024,13714135.0,1048315.0,NaN
442,Brasil,NaN,NaN,76,NaN,NaN,NaN,2021-05-10,19,210147125.0,15209990,25200,423229,889,13759125.0,1027636.0,NaN
443,Brasil,NaN,NaN,76,NaN,NaN,NaN,2021-05-11,19,210147125.0,15282705,72715,425540,2311,13847191.0,1009974.0,NaN
444,Brasil,NaN,NaN,76,NaN,NaN,NaN,2021-05-12,19,210147125.0,15359397,76692,428034,2494,13924217.0,1007146.0,NaN
445,Brasil,NaN,NaN,76,NaN,NaN,NaN,2021-05-13,19,210147125.0,15433989,74592,430417,2383,13979329.0,1024243.0,NaN

In [11]:
df_brasil.to_csv("./dataset/df_brasil.csv")
df_states.to_csv("./dataset/df_states.csv")